### ISSUE TITLE
Enforce `import` at the top

### ISSUE THREAD

**Issue by sindresorhus** [jfmengels/eslint-plugin-import-order#11]
According to the ES2015 spec the `import` keyword should always be at the top. Would be useful to have a rule to enforce this for early warning in the editor and for Babel, which doesn't seem to enforce it.

**Comment by jamestalmage** [comment]
Babel enforces only the minimum of the language specification (that they be top level):

``` js
import test from 'ava';

test(t => {
  import fn from '../';
});
```

produces:

```
SyntaxError: file.js: 'import' and 'export' may only appear at the top level
```

AFAIK, import statements can appear anywhere in the top level code block. However, there is no reason not to put them at the top of the file. Import statements are hoisted, so Babel will relocate them to the top anyways when converting to `require` statements.

+1 from me.

**Comment by sindresorhus** [comment]
[It seems I was wrong.](http://exploringjs.com/es6/ch_modules.html#_imports-and-exports-must-be-at-the-top-level) Pretty sure it was true at some point though. `import` can indeed be anywhere at the top-level. I still think this rule could be useful and I see no good reason why you wouldn't want them to be at the top.

**Comment by jamestalmage** [comment]
Agreed - even more so _because_ of hoisting. This rule enforces your code to look the way it behaves.

**Comment by sindresorhus** [comment]
Moved to https://github.com/benmosher/eslint-plugin-import/issues/253.
