### ISSUE TITLE
Ignore imports without a variable

### ISSUE THREAD

**Issue by sindresorhus** [jfmengels/eslint-plugin-import-order#5]
``` js
require('loud-rejection');
```

``` js
import 'loud-rejection';
```

These usually mutate some state and should allowed to be placed anywhere.

**Comment by jfmengels** [comment]
Hmm... not sure how I feel about that (especially as I really don't like those kind of imports :p). 

The fact that it does not need a variable is not a reason to have it elsewhere. That said, I agee that this may look a bit prettier/clearer

``` js
var fs = require('fs');
var _ = require('lodash');
var foo = require('./foo');

require('loud-rejection');
require('./promisify-stuff');
```

I'm not sure whether to ignore them as per your suggestion, add a flag to ignore those without variables, or to add a new option allowing to have two piles of imports : normal and side-effectsy ones (each of them in the requested order).

Opinions from passerbys?

**Comment by sindresorhus** [comment]
// @jamestalmage @SamVerschueren

**Comment by SamVerschueren** [comment]
> These usually mutate some state and should allowed to be placed anywhere.

Totally agree. Use it myself and the order that they are imported might be relevant. An example is the babel require hook which should be imported first.

**Comment by jfmengels** [comment]
Okay, sounds good. Will disable it, and I'll add an option later if people request it.

**Comment by jamestalmage** [comment]
> the order that they are imported might be relevant

:+1: That argument is the clincher

**Comment by forivall** [comment]
:+1: another common one is `import 'source-map-support/register'`
