### ISSUE TITLE
Publish new patch to npm for the latest REAME.md

### ISSUE THREAD

**Issue by dlmr** [jfmengels/eslint-plugin-import-order#6]
The README that currently is available at [npm](https://www.npmjs.com/package/eslint-plugin-import-order) is out of date with the master on this repository.

Most notably the **rule** is incorrect leading to the user getting the following error:

```
  1:1  error  Definition for rule 'import-order' was not found  import-order
```

Publishing a new version will avoid this confusion.

**Comment by jfmengels** [comment]
I was waiting for (expecting) issues to pop in order to re-publish, but seems like it's working fine (except what you reported).

I just published 2.1.2. Sorry for the confusion
