### ISSUE TITLE
Autofix

### ISSUE THREAD

**Issue by sindresorhus** [jfmengels/eslint-plugin-import-order#7]
Would be so nice if this plugin supported autofixing.

**Comment by jamestalmage** [comment]
Unfortunately, ESLint has some pretty strict rules regarding fixes: http://eslint.org/docs/developer-guide/working-with-rules#applying-fixes

> Best practices for fixes:
> 1. Make fixes that are as small as possible. Anything more than a single character is risky and could prevent other, simpler fixes from being made.
> 2. Only make one fix per message. This is enforced because you must return the result of the fixer operation from fix().
> 3. Fixes should not introduce clashes with other rules. You can accidentally introduce a new problem that won’t be reported until ESLint is run again. Another good reason to make as small a fix as possible.

 The "one fix per message" enforcement kills this idea. You need two changes per message (delete the node, and add it back later).

Maybe a codemod instead?

**Comment by jamestalmage** [comment]
> Maybe a codemod instead?

We could auto-run the codemod in XO

**Comment by jfmengels** [comment]
I agree that it would be nice to have autofix for this (and plenty of rules...)

> Make fixes that are as small as possible. Anything more than a single character is risky and could prevent other, simpler fixes from being made.

But to me, this here above is a good reason to not do it. But there's some discussion on the topic https://github.com/eslint/eslint/issues/5329, so I prefer waiting for whatever might come out of it. This is also one of the reasons why I haven't worked on the autofix for eslint-plugin-ava

> We could auto-run the codemod in XO

Slow... :s

**Comment by sindresorhus** [comment]
> But there's some discussion on the topic eslint/eslint#5329, so I prefer waiting for whatever might come out of it.

:+1: Yeah. Let's just keep this issue open until then.

> This is also one of the reasons why I haven't worked on the autofix for eslint-plugin-ava

It's probably going to take a good while though, so I think we could at least add autofix now for what's possible.

> We could auto-run the codemod in XO

Would be cool to at least experiment with this. I think there's always going to be something that is not possible with the ESLint fixer thing.

> Slow... :s

If we somehow could get the AST from ESLint we wouldn't have to reparse it and could instead just convert it to the Babel AST ([`babel-eslint`](https://github.com/babel/babel-eslint)?).

**Comment by jamestalmage** [comment]
Actually, it would mean converting to `recast`, which I believe is easier. Recast actually handles output from both esprima and acorn already (you need to run an extra step to attach comments and whitespace).

Recast is likely to be way better about honoring existing code style also. 

At a minimum, it's a novel idea. 

@benjamn - what do you think?

**Comment by jfmengels** [comment]
Closing this, as I've deprecated this plugin in favor of using [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import).
